### ISSUE TITLE
Error with pREST (Docs is not very clear about it)

### ISSUE THREAD

**Issue by AJDSB** [prest/prest#297] opened 2018-04-28 06:17 UTC
pREST version (or commit ref): 4.0
pREST endpoint:
PostgreSQL version: 10.3
Operating system: Windows 10 (client machine where I have pREST binary)
Go version: none
Log gist:

## Description
Am confused with the installation part and subsequently on how it is working. I have downloaded the binary file and set it with the prest.toml file as mentioned in snap:
![image](https://user-images.githubusercontent.com/32528877/39392745-03d33de2-4ad9-11e8-8eb1-a02ad46a1626.png)

Now when i execute the installed binary through cmd.exe, i get the following 

![image](https://user-images.githubusercontent.com/32528877/39392758-3d15e76c-4ad9-11e8-986e-5d4ecdd913ac.png)

Hoping that pREST is running, i tried http://127.0.0.1:8000/databases , http://127.0.0.1:8000/postgres/public/Mytable but am getting the below error 

![image](https://user-images.githubusercontent.com/32528877/39392782-c02911ba-4ad9-11e8-96a5-3085a853b3d2.png)

Kindly help as am new to this.

Thanks and Regards
AJ

**Comment by marioidival** [comment] 2018-04-28 10:50
Do you can show your `prest.toml` file? @AJDSB

**Comment by AJDSB** [comment] 2018-04-28 11:30
Please ignore my last mail.

Hi Mario,
Thank you for the support,

I do not have the file as of now but the configuration of tool is as below :


PREST_DEBUG = true

migrations = "./migrations" [http] port = 6000 [jwt] key = "secret" algo =
"HS256" [pg] host = "127.0.0.1" user = "postgres" pass = "cdma@123" port =
5432 database = "postgres" [ssl] mode = "disable" sslcert = "./PATH" sslkey
= "./PATH" sslrootcert = "./PATH"

[jwt] default = false

Regards
AJ

**Comment by marioidival** [comment] 2018-04-28 12:07
This error happens because in your `prest.toml` file has 2 section named as `jwt`, so to fixed just unify them. @AJDSB

**Comment by AJDSB** [comment] 2018-04-30 06:03
Hi Mario,
Thank you for the support,

Tried as you suggested but still got the same error.
Let me explain the process again that am following , which may help solve the issue:

To begin with am following https://postgres.rest/getting-started/installation/ 
I started with downloading the binary for windows from git https://github.com/prest/prest/releases/download/v0.3.0/prest-windows-4.0-amd64.exe 
then I created a prest.toml and saved it along with the binary file in folder on desktop. the configuration prest.toml as below :

PREST_DEBUG=true
migrations = "./migrations"
[http]
port = 6000
[jwt]
key = "secret"
algo = "HS256"
default = false
[pg]
host = "127.0.0.1"
user = "postgres"
pass = "cdma@123"
port = 5432
database = "postgres"
[ssl]
mode = "disable"
sslcert = "./PATH"
sslkey = "./PATH"
sslrootcert = "./PATH"

I open the cmd from the folder I saved both the above files and from there I executed the binary file. The message received is:

 

And then I tried the command on browser  http://127.0.0.1:6000/databases .

NOTE: Things that might be missing ….
As I informed above the official documentation that am using, as per that after excuting the binary file, I must follow as per the snapshot from the official website and which seems the step that am missing.
And then move to configuration where we need to configure the prest.toml file.

 


Also my database snapshot is as below :
 


Please help explain the installation process as am totally stuck.
With Thanks and Regards
AJ

**Comment by AJDSB** [comment] 2018-04-30 06:08
Hi Mario,
Thank you for the support,

Tried as you suggested but still got the same error.
Let me explain the process again that am following , which may help solve the issue:

To begin with am following https://postgres.rest/getting-started/installation/ 
I started with downloading the binary for windows from git https://github.com/prest/prest/releases/download/v0.3.0/prest-windows-4.0-amd64.exe 
then I created a prest.toml and saved it along with the binary file in folder on desktop. the configuration prest.toml as below :

PREST_DEBUG=true
migrations = "./migrations"
[http]
port = 6000
[jwt]
key = "secret"
algo = "HS256"
default = false
[pg]
host = "127.0.0.1"
user = "postgres"
pass = "cdma@123"
port = 5432
database = "postgres"
[ssl]
mode = "disable"
sslcert = "./PATH"
sslkey = "./PATH"
sslrootcert = "./PATH"

I open the cmd from the folder I saved both the above files and from there I executed the binary file. The message received is:

![image](https://user-images.githubusercontent.com/32528877/39416486-f1abf936-4c6a-11e8-8266-7ad809ba807c.png)

And then I tried the command on browser  http://127.0.0.1:6000/databases .

NOTE: Things that might be missing ….
As I informed above the official documentation that am using, as per that after excuting the binary file, I must follow as per the snapshot from the official website and which seems the step that am missing.
And then move to configuration where we need to configure the prest.toml file.
 
![image](https://user-images.githubusercontent.com/32528877/39416456-ba2782dc-4c6a-11e8-9271-0989c9dce563.png)

Also my database snapshot is as below :
 
![image](https://user-images.githubusercontent.com/32528877/39416475-d5e42a5c-4c6a-11e8-903e-5cbc005f7be0.png)

Please help explain the installation process as am totally stuck.
With Thanks and Regards
AJ

**Comment by felipeweb** [comment] 2018-05-02 13:28
@AJDSB what is the output on the databases endpoint?

**Comment by felipeweb** [comment] 2018-05-02 13:38
@AJDSB Sorry i misunderstood something, of course the documentation need to be improved. Do you want to send a pull request in docs with the improvement? 

The toml file is not mandatory, if you want you can use environment variables to configure pREST. By default JWT is enable. If you do not want JWT, can use JWT_DEFAULT=false as an environment variable.

**Comment by AJDSB** [comment] 2018-05-03 11:24
Hi Felipe,

Thank you for the support.

I believe my issue is not with the toml file instead am not getting how to
proceed with the part "Running pREST with the pre-existing database." .
Where do i need to define or pass these variables.

Regards
Anurag

**Comment by AJDSB** [comment] 2018-05-07 09:10
Hi Felipe/Mario,

Any updates.

Thanks
Anurag

**Comment by jtemporal** [comment] 2018-05-07 13:40
Hi @AJDSB the problem is the port! The `6000` port is blocked on windows 😉 

Try changing the port on `prest.toml` to `8080` and then access `http://localhost:8080/databases/` on your browser:

![prest](https://user-images.githubusercontent.com/6595551/39704832-049fcd92-51e3-11e8-9542-8b64358f42b0.PNG)

Try that and let me know what is the outcome please.

**Comment by AJDSB** [comment] 2018-05-09 04:02
Hi Jessica,

Thank you for the support.

I changes the port as you suggested and it worked. Thanks a ton for
helping😀

Regards
AJ

**Comment by jtemporal** [comment] 2018-05-09 13:34
Great @AJDSB :tada: glad to hear it worked!

I'm closing this one in favor of #301 :wink:

**Closed by jtemporal** 2018-05-09 13:34 UTC
Labels: docs
