### ISSUE TITLE
JOIN query only works for some table combinations

### ISSUE THREAD

**Issue by manhofer** [prest/prest#718] opened 2022-09-12 11:47 UTC
**Describe the bug**
When I try to create a JOIN get request, it works for some combinations of database tables and for some I get this error:

`"could not perform JoinByRequest: Invalid identifier"`

I am using Postman to send the query. Credentials and URL are all okay.

(1) Here is a query that does work:
`<db_url>/public/bodyfat?_join=inner:model_fitting_results:bodyfat.fitting_id:$eq:bodyfat.fitting_id
`
(2) And this one does not:
`<db_url>/public/reconstruction_pipeline_eval_results?_join=inner:reconstruction_pipeline_results:reconstruction_pipeline_eval_results.reconstruction_pipeline_results_id:$eq:reconstruction_pipeline_results.reconstruction_pipeline_results_id`

In case (1) I link the tables `bodyfat` and `model_fitting_results` via the `fitting_id` field (which is primary key in `model_fitting_results`, and foreign key in `bodyfat`).
In case (2) I do basically the same: `reconstruction_pipeline_eval_results` linked with `reconstruction_pipeline_results` via `reconstruction_pipeline_results_id`.

All data is correct in the database tables, and the two queries both work when executing them via SQL on the database directly and not via the API. Could it be that the second query is too long?

Thanks for the help in advance!

**Desktop (please complete the following information):**
 - pREST version (or commit ref): v1.0.14
 - pREST endpoint: /{DATABASE}/{SCHEMA}/{TABLE}
 - PostgreSQL version: 13.5
 - deployed on a Kubernetes cluster as per https://github.com/prest/prest/tree/main/install-manifests

**Comment by vmesel** [comment] 2022-10-28 16:19
@manhofer can you provide us the table schemas, so we can replicate the error?

**Comment by vmesel** [comment] 2022-11-09 01:19
Awesome, I'll work on that later this week! Thank you for sharing.

**Comment by vmesel** [comment] 2022-11-09 14:12
@manhofer I think there are lots of things that can be related to this issue. Try updating your pREST to 1.1.4, we've changed an aggregation part for better querying performance. Before, we were using `json_agg` database function to serialize all data and send it to the golang backend.

**Comment by kalmarz** [comment] 2022-11-09 14:39
@vmesel we run it in Kubernetes and have a test instance that runs the [latest and greatest?](https://hub.docker.com/layers/prest/prest/v1/images/sha256-e709ce16146e0be98c642d65e830f9ce35e1b91aaecef46b416faead52387337?context=explore) from Docker Hub...
... and it gives the same error.
I will give a try by building a new image from source but unless I miss something 1.1.2 is the latest release on GH.

**Comment by vmesel** [comment] 2022-11-09 14:50
@kalmarz, don't even bother to do that. I found the issue: So the problem is that our `chkInvalidIdentifier` function takes a column name with a maximum length of 63 characters. @avelino, @arxdsilva, and @fabriziomello can you help me over here, so we can fix this?

I think that we need to support a user setting for this one, as `NAMEDATALEN` is configurable by the user.

Here is the docs from pSQL: https://www.postgresql.org/docs/current/runtime-config-preset.html

And our function

```
func chkInvalidIdentifier(identifer ...string) bool {
	for _, ival := range identifer {
		if ival == "" || len(ival) > 63 || unicode.IsDigit([]rune(ival)[0]) {
```

**Comment by vmesel** [comment] 2022-11-09 16:01
@manhofer @kalmarz, thanks for reporting the bug! I was able to run a quick fix over here and I would like to validate if it works with you. Can you guys clone this branch from my fork? https://github.com/vmesel/prest/tree/check/issue-718

**Comment by vmesel** [comment] 2022-11-11 00:14
@manhofer the fix for this request is already available on the latest version of the software.

**Closed by vmesel** 2022-11-11 00:14 UTC
Labels: bug, product/api-server

**Comment by kalmarz** [comment] 2022-11-15 09:50
Thank you Gents. I'm wondering if there's a chance to publish a new stable Docker image to a public registry?
